insert into public.economic_event_series (
  series_key,
  name,
  country,
  currency,
  category,
  event_kind,
  frequency,
  unit,
  official_source_name,
  official_source_url,
  source_connector,
  base_impact_score,
  ranking_notes,
  is_active,
  metadata
)
values
  (
    'us-real-gdp-qoq',
    'Real GDP QoQ',
    'United States',
    'USD',
    'Growth',
    'data',
    'Quarterly',
    '%',
    'U.S. Bureau of Economic Analysis',
    'https://www.bea.gov/data/gdp/gross-domestic-product',
    'bea',
    90,
    'Headline quarterly real economic growth, reported at a seasonally adjusted annual rate.',
    true,
    jsonb_build_object(
      'dataset', 'NIPA',
      'table_name', 'T10101',
      'line_number', '1',
      'release_family', 'GDP'
    )
  ),
  (
    'us-pce-price-index-mom',
    'PCE Price Index MoM',
    'United States',
    'USD',
    'Inflation',
    'data',
    'Monthly',
    '%',
    'U.S. Bureau of Economic Analysis',
    'https://www.bea.gov/data/personal-consumption-expenditures-price-index',
    'bea',
    85,
    'Monthly change in the headline PCE price index.',
    true,
    jsonb_build_object(
      'dataset', 'NIPA',
      'table_name', 'T20804',
      'line_description', 'Personal consumption expenditures (PCE)',
      'release_family', 'Personal Income and Outlays'
    )
  ),
  (
    'us-pce-price-index-yoy',
    'PCE Price Index YoY',
    'United States',
    'USD',
    'Inflation',
    'data',
    'Monthly',
    '%',
    'U.S. Bureau of Economic Analysis',
    'https://www.bea.gov/data/personal-consumption-expenditures-price-index',
    'bea',
    85,
    'Annual change in the headline PCE price index.',
    true,
    jsonb_build_object(
      'dataset', 'NIPA',
      'table_name', 'T20804',
      'line_description', 'Personal consumption expenditures (PCE)',
      'release_family', 'Personal Income and Outlays'
    )
  ),
  (
    'us-core-pce-price-index-mom',
    'Core PCE Price Index MoM',
    'United States',
    'USD',
    'Inflation',
    'data',
    'Monthly',
    '%',
    'U.S. Bureau of Economic Analysis',
    'https://www.bea.gov/data/personal-consumption-expenditures-price-index-excluding-food-and-energy',
    'bea',
    95,
    'Monthly change in the PCE price index excluding food and energy.',
    true,
    jsonb_build_object(
      'dataset', 'NIPA',
      'table_name', 'T20804',
      'line_description', 'PCE excluding food and energy',
      'release_family', 'Personal Income and Outlays'
    )
  ),
  (
    'us-core-pce-price-index-yoy',
    'Core PCE Price Index YoY',
    'United States',
    'USD',
    'Inflation',
    'data',
    'Monthly',
    '%',
    'U.S. Bureau of Economic Analysis',
    'https://www.bea.gov/data/personal-consumption-expenditures-price-index-excluding-food-and-energy',
    'bea',
    95,
    'Annual change in the PCE price index excluding food and energy.',
    true,
    jsonb_build_object(
      'dataset', 'NIPA',
      'table_name', 'T20804',
      'line_description', 'PCE excluding food and energy',
      'release_family', 'Personal Income and Outlays'
    )
  ),
  (
    'us-personal-income-mom',
    'Personal Income MoM',
    'United States',
    'USD',
    'Growth',
    'data',
    'Monthly',
    '%',
    'U.S. Bureau of Economic Analysis',
    'https://www.bea.gov/data/income-saving/personal-income',
    'bea',
    75,
    'Monthly change in personal income.',
    true,
    jsonb_build_object(
      'dataset', 'NIPA',
      'table_name', 'T20100',
      'line_description', 'Personal income',
      'release_family', 'Personal Income and Outlays'
    )
  ),
  (
    'us-personal-spending-mom',
    'Personal Spending MoM',
    'United States',
    'USD',
    'Growth',
    'data',
    'Monthly',
    '%',
    'U.S. Bureau of Economic Analysis',
    'https://www.bea.gov/data/income-saving/personal-income',
    'bea',
    75,
    'Monthly change in personal consumption expenditures.',
    true,
    jsonb_build_object(
      'dataset', 'NIPA',
      'table_name', 'T20100',
      'line_description', 'Personal consumption expenditures',
      'release_family', 'Personal Income and Outlays'
    )
  )
on conflict (series_key) do update set
  name = excluded.name,
  category = excluded.category,
  event_kind = excluded.event_kind,
  frequency = excluded.frequency,
  unit = excluded.unit,
  official_source_name = excluded.official_source_name,
  official_source_url = excluded.official_source_url,
  source_connector = excluded.source_connector,
  base_impact_score = excluded.base_impact_score,
  ranking_notes = excluded.ranking_notes,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  updated_at = now();
