insert into public.economic_event_series (
  series_key,
  name,
  country,
  currency,
  category,
  event_kind,
  frequency,
  unit,
  official_source_name,
  official_source_url,
  source_connector,
  base_impact_score,
  ranking_notes,
  is_active,
  metadata
)
values
  (
    'us-initial-jobless-claims',
    'Initial Jobless Claims',
    'United States',
    'USD',
    'Labour',
    'data',
    'Weekly',
    'claims',
    'U.S. Department of Labor, Employment and Training Administration',
    'https://oui.doleta.gov/unemploy/claims.asp',
    'dol',
    80,
    'Seasonally adjusted initial unemployment-insurance claims, released weekly on Thursday.',
    true,
    jsonb_build_object('report', 'UI Weekly Claims', 'measure', 'SA')
  ),
  (
    'us-continuing-jobless-claims',
    'Continuing Jobless Claims',
    'United States',
    'USD',
    'Labour',
    'data',
    'Weekly',
    'claims',
    'U.S. Department of Labor, Employment and Training Administration',
    'https://oui.doleta.gov/unemploy/claims.asp',
    'dol',
    65,
    'Seasonally adjusted continued unemployment-insurance claims, released weekly on Thursday.',
    true,
    jsonb_build_object('report', 'UI Weekly Claims', 'measure', 'SA')
  )
on conflict (series_key) do update set
  name = excluded.name,
  category = excluded.category,
  event_kind = excluded.event_kind,
  frequency = excluded.frequency,
  unit = excluded.unit,
  official_source_name = excluded.official_source_name,
  official_source_url = excluded.official_source_url,
  source_connector = excluded.source_connector,
  base_impact_score = excluded.base_impact_score,
  ranking_notes = excluded.ranking_notes,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  updated_at = now();
