insert into public.economic_event_series (
  series_key,
  name,
  country,
  currency,
  category,
  event_kind,
  frequency,
  unit,
  official_source_name,
  official_source_url,
  source_connector,
  base_impact_score,
  ranking_notes,
  is_active,
  metadata
)
values
  (
    'us-adp-private-employment',
    'ADP National Employment Report',
    'United States',
    'USD',
    'Labour',
    'data',
    'Monthly',
    'Jobs',
    'ADP Research',
    'https://adpemploymentreport.com/',
    'adp',
    70,
    'Monthly change in U.S. private employment from the official ADP report.',
    true,
    jsonb_build_object('report_data_url', 'https://adpemploymentreport.com/ner_production.json')
  ),
  (
    'us-nar-existing-home-sales',
    'Existing Home Sales',
    'United States',
    'USD',
    'Housing',
    'data',
    'Monthly',
    'Million units',
    'National Association of REALTORS',
    'https://www.nar.realtor/research-and-statistics/housing-statistics/existing-home-sales',
    'nar',
    65,
    'Seasonally adjusted annual rate of existing-home sales.',
    true,
    jsonb_build_object('release_schedule_url', 'https://www.nar.realtor/press-releases/nar-statistical-news-release-schedule')
  ),
  (
    'us-nar-pending-home-sales',
    'Pending Home Sales',
    'United States',
    'USD',
    'Housing',
    'data',
    'Monthly',
    'Index',
    'National Association of REALTORS',
    'https://www.nar.realtor/research-and-statistics/housing-statistics/pending-home-sales',
    'nar',
    55,
    'Pending Home Sales Index for signed residential contracts.',
    true,
    jsonb_build_object('release_schedule_url', 'https://www.nar.realtor/press-releases/nar-statistical-news-release-schedule')
  ),
  (
    'us-ny-empire-state-manufacturing',
    'NY Empire State Manufacturing Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.newyorkfed.org/survey/empire/empiresurvey_overview.html',
    'regional-fed',
    55,
    'General business conditions index from the New York Fed Empire State Manufacturing Survey.',
    true,
    jsonb_build_object('value_column', 'GACDSA')
  ),
  (
    'us-philadelphia-fed-manufacturing',
    'Philadelphia Fed Manufacturing Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.philadelphiafed.org/surveys-and-data/regional-economic-analysis/manufacturing-business-outlook-survey',
    'regional-fed',
    55,
    'General business activity diffusion index from the Philadelphia Fed Manufacturing Business Outlook Survey.',
    true,
    jsonb_build_object('value_column', 'GAC')
  ),
  (
    'us-dallas-fed-manufacturing',
    'Dallas Fed Manufacturing Activity Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.dallasfed.org/research/surveys/tmos',
    'regional-fed',
    45,
    'Production balance index from the Dallas Fed Texas Manufacturing Outlook Survey.',
    true,
    jsonb_build_object(
      'survey_url', 'https://www.dallasfed.org/research/surveys/tmos',
      'values_source', 'Official Dallas Fed report results table'
    )
  ),
  (
    'us-dallas-fed-services',
    'Dallas Fed Services Revenue Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.dallasfed.org/research/surveys/tssos',
    'regional-fed',
    40,
    'Revenue balance index from the Dallas Fed Texas Service Sector Outlook Survey.',
    true,
    jsonb_build_object(
      'survey_url', 'https://www.dallasfed.org/research/surveys/tssos',
      'values_source', 'Official Dallas Fed report results table'
    )
  ),
  (
    'us-richmond-fed-manufacturing',
    'Richmond Fed Manufacturing Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.richmondfed.org/region_communities/regional_data_analysis/business_surveys/manufacturing',
    'regional-fed',
    45,
    'Composite manufacturing index from the Federal Reserve Bank of Richmond survey.',
    true,
    jsonb_build_object(
      'survey_url', 'https://www.richmondfed.org/region_communities/regional_data_analysis/business_surveys/manufacturing',
      'schedule_url', 'https://www.richmondfed.org/region_communities/regional_data_analysis/business_surveys/manufacturing/release_schedule',
      'values_source', 'Official Richmond Fed release headline'
    )
  ),
  (
    'us-kansas-city-fed-manufacturing',
    'Kansas City Fed Manufacturing Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.kansascityfed.org/surveys/manufacturing-survey/',
    'regional-fed',
    45,
    'Composite manufacturing index from the Federal Reserve Bank of Kansas City survey.',
    true,
    jsonb_build_object(
      'survey_url', 'https://www.kansascityfed.org/surveys/manufacturing-survey/',
      'schedule_url', 'https://www.kansascityfed.org/surveys/manufacturing-survey/manufacturing-survey-release-dates/',
      'values_source', 'Official Kansas City Fed historical monthly workbook'
    )
  ),
  (
    'us-sp-global-manufacturing-pmi',
    'S&P Global Manufacturing PMI',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'S&P Global',
    'https://www.pmi.spglobal.com/Public/Release/ReleaseDates',
    'regional-fed',
    50,
    'U.S. manufacturing PMI release from S&P Global; official public value retrieval is not available to this connector.',
    true,
    jsonb_build_object(
      'release_schedule_url', 'https://www.pmi.spglobal.com/Public/Release/ReleaseDates',
      'values_not_synced', true,
      'link_only', true
    )
  ),
  (
    'us-chicago-business-barometer',
    'Chicago PMI (Business Barometer)',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'ISM Chicago / MNI Indicators',
    'https://chicago.ismworld.org/news-publications/reports/research-survey/',
    'regional-fed',
    45,
    'Chicago Business Barometer release; official public value retrieval is not available to this connector.',
    true,
    jsonb_build_object(
      'release_schedule_url', 'https://chicago.ismworld.org/news-publications/reports/research-survey/',
      'values_not_synced', true,
      'link_only', true
    )
  )
on conflict (series_key) do update set
  name = excluded.name,
  category = excluded.category,
  event_kind = excluded.event_kind,
  frequency = excluded.frequency,
  unit = excluded.unit,
  official_source_name = excluded.official_source_name,
  official_source_url = excluded.official_source_url,
  source_connector = excluded.source_connector,
  base_impact_score = excluded.base_impact_score,
  ranking_notes = excluded.ranking_notes,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  updated_at = now();
