insert into public.economic_event_series (
  series_key,
  name,
  country,
  currency,
  category,
  event_kind,
  frequency,
  unit,
  official_source_name,
  official_source_url,
  source_connector,
  base_impact_score,
  ranking_notes,
  is_active,
  metadata
)
values
  (
    'us-treasury-monthly-statement',
    'Monthly Treasury Statement',
    'United States',
    'USD',
    'Fiscal Policy',
    'data',
    'Monthly',
    null,
    'U.S. Department of the Treasury',
    'https://fiscaldata.treasury.gov/datasets/monthly-treasury-statement/',
    'treasury',
    70,
    'Monthly federal receipts, outlays, deficit and financing information.',
    true,
    jsonb_build_object('dataset_id', '015-BFS-2014Q1-13')
  ),
  (
    'us-treasury-daily-statement',
    'Daily Treasury Statement',
    'United States',
    'USD',
    'Fiscal Policy',
    'data',
    'Daily',
    null,
    'U.S. Department of the Treasury',
    'https://fiscaldata.treasury.gov/datasets/daily-treasury-statement/',
    'treasury',
    35,
    'Daily federal operating cash and debt activity.',
    true,
    jsonb_build_object('dataset_id', '015-BFS-2014Q1-03')
  ),
  (
    'us-treasury-monthly-public-debt',
    'Monthly Statement of Public Debt',
    'United States',
    'USD',
    'Fiscal Policy',
    'data',
    'Monthly',
    null,
    'U.S. Department of the Treasury',
    'https://fiscaldata.treasury.gov/datasets/monthly-statement-public-debt/',
    'treasury',
    40,
    'Monthly statement of federal public debt outstanding.',
    true,
    jsonb_build_object('dataset_id', '015-BFS-2014Q1-11')
  ),
  (
    'us-treasury-debt-to-the-penny',
    'Debt to the Penny',
    'United States',
    'USD',
    'Fiscal Policy',
    'data',
    'Daily',
    null,
    'U.S. Department of the Treasury',
    'https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/',
    'treasury',
    30,
    'Daily total public debt outstanding.',
    true,
    jsonb_build_object('dataset_id', '015-BFS-2014Q3-065')
  ),
  (
    'us-treasury-securities-auctions',
    'Treasury Securities Auctions',
    'United States',
    'USD',
    'Financial Markets',
    'data',
    'Multiple per week',
    null,
    'U.S. Department of the Treasury',
    'https://fiscaldata.treasury.gov/datasets/treasury-securities-auctions-data/',
    'treasury',
    55,
    'Treasury securities auction release and auction-result data.',
    true,
    jsonb_build_object('dataset_id', '015-BFS-2014Q3-045')
  )
on conflict (series_key) do update set
  name = excluded.name,
  category = excluded.category,
  event_kind = excluded.event_kind,
  frequency = excluded.frequency,
  unit = excluded.unit,
  official_source_name = excluded.official_source_name,
  official_source_url = excluded.official_source_url,
  source_connector = excluded.source_connector,
  base_impact_score = excluded.base_impact_score,
  ranking_notes = excluded.ranking_notes,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  updated_at = now();
