insert into public.economic_event_series (
  series_key,
  name,
  country,
  currency,
  category,
  event_kind,
  frequency,
  unit,
  official_source_name,
  official_source_url,
  source_connector,
  base_impact_score,
  ranking_notes,
  is_active,
  metadata
)
values
  (
    'us-adp-private-employment',
    'ADP National Employment Report',
    'United States',
    'USD',
    'Labour',
    'data',
    'Monthly',
    'Jobs',
    'ADP Research',
    'https://adpemploymentreport.com/',
    'adp',
    70,
    'Monthly change in U.S. private employment from the official ADP report.',
    true,
    jsonb_build_object('report_data_url', 'https://adpemploymentreport.com/ner_production.json')
  ),
  (
    'us-nar-existing-home-sales',
    'Existing Home Sales',
    'United States',
    'USD',
    'Housing',
    'data',
    'Monthly',
    'Million units',
    'National Association of REALTORS',
    'https://www.nar.realtor/research-and-statistics/housing-statistics/existing-home-sales',
    'nar',
    65,
    'Seasonally adjusted annual rate of existing-home sales.',
    true,
    jsonb_build_object('release_schedule_url', 'https://www.nar.realtor/press-releases/nar-statistical-news-release-schedule')
  ),
  (
    'us-nar-pending-home-sales',
    'Pending Home Sales',
    'United States',
    'USD',
    'Housing',
    'data',
    'Monthly',
    'Index',
    'National Association of REALTORS',
    'https://www.nar.realtor/research-and-statistics/housing-statistics/pending-home-sales',
    'nar',
    55,
    'Pending Home Sales Index for signed residential contracts.',
    true,
    jsonb_build_object('release_schedule_url', 'https://www.nar.realtor/press-releases/nar-statistical-news-release-schedule')
  ),
  (
    'us-ny-empire-state-manufacturing',
    'NY Empire State Manufacturing Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.newyorkfed.org/survey/empire/empiresurvey_overview.html',
    'regional-fed',
    55,
    'General business conditions index from the New York Fed Empire State Manufacturing Survey.',
    true,
    jsonb_build_object('value_column', 'GACDSA')
  ),
  (
    'us-philadelphia-fed-manufacturing',
    'Philadelphia Fed Manufacturing Index',
    'United States',
    'USD',
    'Business Survey',
    'data',
    'Monthly',
    'Index',
    'Federal Reserve Regional Surveys',
    'https://www.philadelphiafed.org/surveys-and-data/regional-economic-analysis/manufacturing-business-outlook-survey',
    'regional-fed',
    55,
    'General business activity diffusion index from the Philadelphia Fed Manufacturing Business Outlook Survey.',
    true,
    jsonb_build_object('value_column', 'GAC')
  )
on conflict (series_key) do update set
  name = excluded.name,
  category = excluded.category,
  event_kind = excluded.event_kind,
  frequency = excluded.frequency,
  unit = excluded.unit,
  official_source_name = excluded.official_source_name,
  official_source_url = excluded.official_source_url,
  source_connector = excluded.source_connector,
  base_impact_score = excluded.base_impact_score,
  ranking_notes = excluded.ranking_notes,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  updated_at = now();
