insert into public.economic_event_series (
  series_key, name, country, currency, category, event_kind, frequency, unit,
  official_source_name, official_source_url, source_connector, base_impact_score,
  ranking_notes, is_active, metadata
)
select
  item.series_key, item.name, item.country, item.currency, item.category, item.event_kind,
  item.frequency, item.unit, item.source_name, item.source_url, item.connector, item.impact,
  item.notes, true, item.metadata::jsonb
from (values
  ('eur-hcob-pmi-flash-manufacturing','Eurozone HCOB Flash Manufacturing PMI','Eurozone','EUR','Business Survey','data','Monthly','Index','S&P Global / HCOB','https://www.pmi.spglobal.com/Public/Release/PressReleases','eurozone-pmi',85,'Flash eurozone manufacturing PMI release; calendar/link-only because PMI values are restricted.'::text,'{"calendar_only":true,"values_not_synced":true,"sector":"manufacturing","variant":"flash","release_calendar_url":"https://www.pmi.spglobal.com/Public/Release/ReleaseDates","hcob_url":"https://www.hcob-bank.com/en/insights/pmi/"}'::text),
  ('eur-hcob-pmi-flash-services','Eurozone HCOB Flash Services PMI','Eurozone','EUR','Business Survey','data','Monthly','Index','S&P Global / HCOB','https://www.pmi.spglobal.com/Public/Release/PressReleases','eurozone-pmi',85,'Flash eurozone services PMI release; calendar/link-only because PMI values are restricted.'::text,'{"calendar_only":true,"values_not_synced":true,"sector":"services","variant":"flash","release_calendar_url":"https://www.pmi.spglobal.com/Public/Release/ReleaseDates","hcob_url":"https://www.hcob-bank.com/en/insights/pmi/"}'::text),
  ('eur-hcob-pmi-flash-composite','Eurozone HCOB Flash Composite PMI','Eurozone','EUR','Business Survey','data','Monthly','Index','S&P Global / HCOB','https://www.pmi.spglobal.com/Public/Release/PressReleases','eurozone-pmi',90,'Flash eurozone composite PMI release; calendar/link-only because PMI values are restricted.'::text,'{"calendar_only":true,"values_not_synced":true,"sector":"composite","variant":"flash","release_calendar_url":"https://www.pmi.spglobal.com/Public/Release/ReleaseDates","hcob_url":"https://www.hcob-bank.com/en/insights/pmi/"}'::text),
  ('eur-hcob-pmi-final-manufacturing','Eurozone HCOB Manufacturing PMI','Eurozone','EUR','Business Survey','data','Monthly','Index','S&P Global / HCOB','https://www.pmi.spglobal.com/Public/Release/PressReleases','eurozone-pmi',85,'Final eurozone manufacturing PMI release; calendar/link-only because PMI values are restricted.'::text,'{"calendar_only":true,"values_not_synced":true,"sector":"manufacturing","variant":"final","release_calendar_url":"https://www.pmi.spglobal.com/Public/Release/ReleaseDates","hcob_url":"https://www.hcob-bank.com/en/insights/pmi/"}'::text),
  ('eur-hcob-pmi-final-services','Eurozone HCOB Services PMI','Eurozone','EUR','Business Survey','data','Monthly','Index','S&P Global / HCOB','https://www.pmi.spglobal.com/Public/Release/PressReleases','eurozone-pmi',85,'Final eurozone services PMI release; calendar/link-only because PMI values are restricted.'::text,'{"calendar_only":true,"values_not_synced":true,"sector":"services","variant":"final","release_calendar_url":"https://www.pmi.spglobal.com/Public/Release/ReleaseDates","hcob_url":"https://www.hcob-bank.com/en/insights/pmi/"}'::text),
  ('eur-hcob-pmi-final-composite','Eurozone HCOB Composite PMI','Eurozone','EUR','Business Survey','data','Monthly','Index','S&P Global / HCOB','https://www.pmi.spglobal.com/Public/Release/PressReleases','eurozone-pmi',90,'Final eurozone composite PMI release; calendar/link-only because PMI values are restricted.'::text,'{"calendar_only":true,"values_not_synced":true,"sector":"composite","variant":"final","release_calendar_url":"https://www.pmi.spglobal.com/Public/Release/ReleaseDates","hcob_url":"https://www.hcob-bank.com/en/insights/pmi/"}'::text),
  ('eur-ecb-stat-hicp','ECB Statistical Release — HICP','Euro Area','EUR','ECB Statistics','data','Monthly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',80,'ECB HICP statistical release calendar; values remain in the ECB Data Portal rather than being collapsed into one calendar value.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"HICP","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-stat-balance-of-payments','ECB Statistical Release — Balance of Payments','Euro Area','EUR','ECB Statistics','data','Monthly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',75,'ECB balance-of-payments and IIP statistical release calendar.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"BPS","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-stat-bank-rates','ECB Statistical Release — Bank Rates','Euro Area','EUR','ECB Statistics','data','Monthly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',75,'ECB bank interest-rate statistical release calendar.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"MIR","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-stat-monetary-developments','ECB Statistical Release — Monetary Developments','Euro Area','EUR','ECB Statistics','data','Monthly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',80,'ECB monetary developments and MFI balance-sheet release calendar.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"BSI","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-stat-bank-lending-survey','ECB Statistical Release — Bank Lending Survey','Euro Area','EUR','ECB Statistics','data','Quarterly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',75,'ECB Bank Lending Survey release calendar.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"BLS","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-stat-government-finance','ECB Statistical Release — Government Finance','Euro Area','EUR','ECB Statistics','data','Quarterly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',70,'ECB government-finance, deficit, debt and government-debt-securities release calendar.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"GFS","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-stat-investment-funds','ECB Statistical Release — Investment Funds','Euro Area','EUR','ECB Statistics','data','Quarterly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',65,'ECB investment-fund statistical release calendar.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"IVF","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-stat-payments','ECB Statistical Release — Payments','Euro Area','EUR','ECB Statistics','data','Quarterly',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',65,'ECB payments and payment-system statistical release calendar.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"PAY","data_portal_url":"https://data.ecb.europa.eu/"}'::text),
  ('eur-ecb-statistical-release','ECB Statistical Release — Other','Euro Area','EUR','ECB Statistics','data','Irregular',null,'European Central Bank','https://www.ecb.europa.eu/press/calendars/statscal/html/index.en.html','ecb-statistics',45,'Official ECB statistical calendar fallback for dataset families not assigned to a named series.'::text,'{"calendar_only":true,"values_not_synced":true,"dataset_family":"other","data_portal_url":"https://data.ecb.europa.eu/"}'::text)
) as item(series_key,name,country,currency,category,event_kind,frequency,unit,source_name,source_url,connector,impact,notes,metadata)
on conflict (series_key) do update set
  name = excluded.name, country = excluded.country, currency = excluded.currency,
  category = excluded.category, event_kind = excluded.event_kind, frequency = excluded.frequency,
  unit = excluded.unit, official_source_name = excluded.official_source_name,
  official_source_url = excluded.official_source_url, source_connector = excluded.source_connector,
  base_impact_score = excluded.base_impact_score, ranking_notes = excluded.ranking_notes,
  is_active = excluded.is_active, metadata = excluded.metadata, updated_at = now();
