insert into public.economic_event_series (
  series_key,
  name,
  country,
  currency,
  category,
  event_kind,
  frequency,
  unit,
  official_source_name,
  official_source_url,
  source_connector,
  base_impact_score,
  ranking_notes,
  is_active,
  metadata
)
values
  (
    'us-fomc-rate-decision',
    'FOMC Interest Rate Decision',
    'United States',
    'USD',
    'Monetary Policy',
    'decision',
    '8 times per year',
    '%',
    'Board of Governors of the Federal Reserve System',
    'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    'federal-reserve',
    100,
    'Federal funds target-range decision from the FOMC.',
    true,
    jsonb_build_object('release_family', 'FOMC')
  ),
  (
    'us-fomc-statement',
    'FOMC Statement',
    'United States',
    'USD',
    'Monetary Policy',
    'document',
    '8 times per year',
    null,
    'Board of Governors of the Federal Reserve System',
    'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    'federal-reserve',
    100,
    'Official policy statement released with the FOMC decision.',
    true,
    jsonb_build_object('release_family', 'FOMC')
  ),
  (
    'us-fomc-press-conference',
    'FOMC Press Conference',
    'United States',
    'USD',
    'Monetary Policy',
    'speech',
    '8 times per year',
    null,
    'Board of Governors of the Federal Reserve System',
    'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    'federal-reserve',
    95,
    'Press conference following selected FOMC policy decisions.',
    true,
    jsonb_build_object('release_family', 'FOMC')
  ),
  (
    'us-fomc-minutes',
    'FOMC Meeting Minutes',
    'United States',
    'USD',
    'Monetary Policy',
    'minutes',
    '8 times per year',
    null,
    'Board of Governors of the Federal Reserve System',
    'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    'federal-reserve',
    85,
    'Official minutes released approximately three weeks after the policy decision.',
    true,
    jsonb_build_object('release_family', 'FOMC')
  ),
  (
    'us-fomc-projections',
    'FOMC Economic Projections',
    'United States',
    'USD',
    'Monetary Policy',
    'document',
    '4 times per year',
    null,
    'Board of Governors of the Federal Reserve System',
    'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    'federal-reserve',
    95,
    'Summary of Economic Projections and dot-plot materials released with selected FOMC decisions.',
    true,
    jsonb_build_object('release_family', 'FOMC')
  ),
  (
    'us-fed-board-speech',
    'Federal Reserve Board Speeches',
    'United States',
    'USD',
    'Monetary Policy',
    'speech',
    'As published',
    null,
    'Board of Governors of the Federal Reserve System',
    'https://www.federalreserve.gov/newsevents/speeches-testimony.htm',
    'federal-reserve',
    75,
    'Official speeches by the Federal Reserve Chair, Vice Chairs, Governors and other Board officials.',
    true,
    jsonb_build_object(
      'release_family', 'Federal Reserve Speeches',
      'archive_url', 'https://www.federalreserve.gov/newsevents/speeches-testimony.htm',
      'direct_document_links', true
    )
  )
on conflict (series_key) do update set
  name = excluded.name,
  category = excluded.category,
  event_kind = excluded.event_kind,
  frequency = excluded.frequency,
  unit = excluded.unit,
  official_source_name = excluded.official_source_name,
  official_source_url = excluded.official_source_url,
  source_connector = excluded.source_connector,
  base_impact_score = excluded.base_impact_score,
  ranking_notes = excluded.ranking_notes,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  updated_at = now();
